# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(341, 292)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 50, 221, 21))
        self.label_1.setObjectName("label_1")
        self.path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.path_input.setGeometry(QtCore.QRect(30, 80, 281, 31))
        self.path_input.setObjectName("path_input")
        self.btn_choose = QtWidgets.QPushButton(self.centralwidget)
        self.btn_choose.setGeometry(QtCore.QRect(230, 50, 101, 21))
        self.btn_choose.setObjectName("btn_choose")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 221, 21))
        self.label_2.setObjectName("label_2")
        self.btn_enc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enc.setGeometry(QtCore.QRect(50, 250, 111, 31))
        self.btn_enc.setObjectName("btn_enc")
        self.btn_dec = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dec.setGeometry(QtCore.QRect(190, 250, 101, 31))
        self.btn_dec.setObjectName("btn_dec")
        # self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        # self.btn_edit.setGeometry(QtCore.QRect(230, 140, 101, 21))
        # self.btn_edit.setObjectName("btn_edit")
        self.copyright = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(30, 170, 281, 51))
        self.copyright.setObjectName("copyright")
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_settings.setGeometry(QtCore.QRect(280, 10, 23, 23))
        self.btn_settings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/visual/img_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon)
        self.btn_settings.setFlat(True)
        self.btn_settings.setObjectName("btn_settings")
        self.btn_help = QtWidgets.QPushButton(self.centralwidget)
        self.btn_help.setGeometry(QtCore.QRect(310, 10, 23, 23))
        self.btn_help.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/visual/img_help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_help.setIcon(icon1)
        self.btn_help.setFlat(True)
        self.btn_help.setObjectName("btn_help")
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_progress = QtWidgets.QLabel(self.centralwidget)
        self.lbl_progress.setGeometry(QtCore.QRect(10, 10, 261, 23))
        self.lbl_progress.setFont(font)
        self.lbl_progress.setText("")
        self.lbl_progress.setObjectName("lbl_progress")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лицензирование видео файлов"))
        self.label_1.setText(_translate("MainWindow", "Защищаемый файл:"))
        self.path_input.setToolTip(_translate("MainWindow", "<html><head/><body><p>Путь к видео файлу</p></body></html>"))
        self.btn_choose.setToolTip(_translate("MainWindow", "<html><head/><body><p>Указать путь к видео файлу-стегоконтейнеру</p></body></html>"))
        self.btn_choose.setText(_translate("MainWindow", "Выбрать"))
        self.label_2.setText(_translate("MainWindow", "Авторская подпись:"))
        self.btn_enc.setText(_translate("MainWindow", "Защитить"))
        self.btn_dec.setText(_translate("MainWindow", "Проверить"))
        # self.btn_edit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Изменить авторскую подпись</p></body></html>"))
        # self.btn_edit.setText(_translate("MainWindow", "Редактировать"))
        self.copyright.setToolTip(_translate("MainWindow", "<html><head/><body><p>Авторская подпись, которая будет встроена в видео файл</p></body></html>"))
        self.copyright.setPlainText(_translate("MainWindow", "Copyright: © [NAME],\n[CREATION_DATE], [OWNER].\nAll Rights Reserved."))
        self.btn_settings.setToolTip(_translate("MainWindow", "<html><head/><body><p>Открыть форму настроек</p></body></html>"))
        self.btn_help.setToolTip(_translate("MainWindow", "<html><head/><body><p>Посмотреть справку</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
